version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: dbCake
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: cakephp_db
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql